spring:
  application:
    name: ms-naissances
  jpa:
    hibernate:
      ddl-auto: validate
    #database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      INDENT_OUTPUT: true
server:
  servlet:
    context-path: /api
  #port: 9191
rsa:
  private-key: classpath:certs/private_key_pkcs8.pem
  public-key: classpath:certs/public_key.pem


